### ISSUE TITLE
Weird almost blank right column

### ISSUE THREAD

**Issue by MicMicMon** [joeattardi/emoji-button#22]
I have a blank column on the right, with only a handful of icons showing up in some lines:

![image](https://user-images.githubusercontent.com/37897072/73054833-b0742780-3e8b-11ea-8151-fe8ce42dede0.png)

![image](https://user-images.githubusercontent.com/37897072/73054854-b79b3580-3e8b-11ea-9c38-32ce8885d5c2.png)

aaaah I think I understand. They are "combined" emojis that are not properly taken into account by the emoji font I have (you can see the plane under the pilot too, or the mic below):

![image](https://user-images.githubusercontent.com/37897072/73055067-3c864f00-3e8c-11ea-8135-b7a3e415eee5.png)

Hum. Not sure how to handle that?

**Comment by MicMicMon** [comment]
It also introduces quite a bit of bad-rendered icons:
![image](https://user-images.githubusercontent.com/37897072/73055177-78211900-3e8c-11ea-8540-5c97041868c9.png)

Maybe we should have a switch to choose which emoji release version we want to stick with, letting time for a vast majority of the userbase to have the new fonts?

**Comment by joeattardi** [comment]
This is definitely a mistake on my part. I should have released the updated emojis in a new major version since it introduces a manner of breaking changes.

I will get this rectified later tonight. I will revert these changes, release a new 2.6.x version containing the bug fix, then will release the new emojis as 3.0.0.

This was a semantic versioning fail on my part.

Sorry about that!

**Comment by MicMicMon** [comment]
Ok great, thanks!

Any idea on how to have all emojis supported for everybody? I can't make total sense of what I read and I'm sure you are very knowledgeable about all that :)

**Comment by joeattardi** [comment]
The OS system fonts have to be updated to support the new emojis. Emojis are a sequence of Unicode code points. For example, the Pilot emoji is a sequence of the Adult emoji and the Airplane emoji, joined by a Unicode Zero Width Joiner character. If, for example, the OS did not recognize this sequence for the Pilot emoji, it would show an Adult emoji next to an AIrplane emoji.

Unfortunately there is fix other than updating the operating system.

**Comment by MicMicMon** [comment]
Ok thanks for the explanation.

Then, I guess a config parameter would be the best option for the emoji set, no?

Because if you release a new breaking change version 3.0.0, it means that a project that sticks with the previous emoji set won't get the future updates / fixes on version 2.x.x - and so on with next emoji updates.

What do you think?

**Comment by joeattardi** [comment]
I like the idea, but that's a tricky one - I am not sure how I would support that. The emoji-datasource package does not specify the version of Unicode each emoji is from. So there'd be no way to choose between different versions.

Within reason, I would support the 2.x.x line with features and bug fixes, at least for a while until it's more likely that people will have the newer emoji support.

I could also look around and see if there's another emoji library that would have the version information. Let me do that and see what's out there.

Thanks for the suggestions!

**Comment by MicMicMon** [comment]
Great! Thanks.

Following the status of [those releases](https://github.com/googlefonts/noto-emoji/releases) might be one of many indicators about wide adoption -- although I don't really know what coverage it might represent.

**Comment by joeattardi** [comment]
Actually, it turns out that emoji-datasource includes the version each emoji was added. So I could most likely add a version option to specify the Emoji version to use!

**Comment by joeattardi** [comment]
I have just released v2.7.0 which includes an `emojiVersion` option.

**Comment by MicMicMon** [comment]
Awesome, thanks!

**Comment by MicMicMon** [comment]
Actually, still have the blank column. I guess that's because I miss a glyph in the "flags" section?

See:

![image](https://user-images.githubusercontent.com/37897072/73125721-5cac3000-3faa-11ea-85ab-d0a1464ea8c7.png)
